### ISSUE TITLE
Replace `Grid::axes` with `Grid::evolve_info`

### ISSUE THREAD

**Issue by cschwan** [NNPDF/pineko#72] opened 2022-12-28 12:07 UTC
`Grid::axes` is too restrictive, see the discussion here: <https://github.com/NNPDF/pineappl/issues/197>. Therefore it should be replaced with `Grid::evolve_info`.

**Comment by scarlehoff** [comment] 2023-03-27 06:13
`axes` and `evolve_info` do not produce exactly the same xgrid in all scenarios.

In order to test #84, I'm regenerating fktables for the whole of theory 400. Doing that I've discovered that for some grids (more explicitly, for `ATLASDY2D8TEV-aMCfast_obs_1.pineappl.lz4`, note that `obs_0` is ok!) `evolve_info` and `axes` return grids of different sizes.

This is independent of the orders selected when asking for `evolve_info`.

Inspecting the two x-grids returned, `axes` and `evolve_info` differ because the grid returned by `axes` repeats two values:

`0.00094688` and `0.00335233`. I'm assuming `evolve_info` is rightly sanitising the results while `axes` is not. All checks of `pineko` pass with flying colors (because the content of `x`s in the grid and the operator is indeed the same). However, during the evolution, pineappl says "no way Jose".

I'm copying the error below although now I think that maybe it is a `pienappl` bug (why are `evolve_info` and `evolve` using a different grid?) or a grid problem (why does the grid repeat one value of x?) or both... @cschwan @AleCandido @felixhekhorn 

The grid is [here](https://github.com/NNPDF/theories/blob/main/data/grids/400/ATLASDY2D8TEV-aMCfast_obs_1.pineappl.lz4). The error occurs independently of whether the eko was computed using `main` or #84 (so, it occurs independently of how the `eko` was computed). 

Python error when using pineko:
```
  File "/media/juacrumar/pinekoing/pineko/src/pineko/evolve.py", line 209, in evolve_grid                                                                                                                             
    fktable = grid.evolve(                           
  File "/media/juacrumar/pinekoing/pinevortex/lib/python3.10/site-packages/pineappl/grid.py", line 338, in evolve                                                                                                     
    self.raw.evolve(                                 
pyo3_runtime.PanicException: Nothing returned from evolution.: EvolutionFailure("operator information does not match grid's x-grid values")  
```

I've tried using the `cli` but I get the following error independently on which branch I used to compute the `eko`.
```
Error: missing field `Q2grid`
```

**Comment by AleCandido** [comment] 2023-03-27 11:47
> Inspecting the two x-grids returned, `axes` and `evolve_info` differ because the grid returned by `axes` repeats two values:
> `0.00094688` and `0.00335233`. I'm assuming `evolve_info` is rightly sanitising the results while `axes` is not.

In principle, the deduplication is almost the same:
https://github.com/NNPDF/pineappl/blob/f2152da2a6b0c387b6b4c999b9025489dc02c580/pineappl/src/grid.rs#L1808-L1809
https://github.com/NNPDF/pineappl/blob/f2152da2a6b0c387b6b4c999b9025489dc02c580/pineappl/src/grid.rs#L1353-L1354

The only differences are in the sorting step:
```rs
# .axes
x_grid.sort_by(|a, b| a.partial_cmp(b).unwrap());
# .evolve_info
x1.sort_by(f64::total_cmp);
```
and that `axes` is deduplicated only just before returning, while `evolve_info` is doing it for each iterated subgrid.

The other major difference is related to your original issue about `Grid::axes`: that is checking all x-grids to be the same for one `(order, bin)`, and concatenating across different `(order, bin)`, while `Grid::evolve_info` is just concatenating them all.

**Comment by cschwan** [comment] 2023-03-28 10:46
It probably can't cope with the new/changed (?) EKO format.

**Comment by AleCandido** [comment] 2023-03-28 11:24
> It probably can't cope with the new/changed (?) EKO format.

https://github.com/NNPDF/pineappl/blob/f2152da2a6b0c387b6b4c999b9025489dc02c580/pineappl_cli/src/evolve.rs#L31

Now called `mu2grid`, because `Q2` was inconsistent...

**Comment by cschwan** [comment] 2023-03-29 07:17
- @scarlehoff where can I get the EKO?
- @AleCandido is the EKO format version documented somewhere?

**Comment by AleCandido** [comment] 2023-03-29 07:33
> * @AleCandido is the EKO format version documented somewhere?

Properly documented, no, I'm sorry.
We still need to make some small changes to account for the numerical FONLL project, and I'm currently updating the runcard format https://github.com/NNPDF/eko/pull/220

However, in principle it is actually pretty simple, and those changes are going to have a minor impact, so I can write it here and actually add to the docs, even if it will be updated and improved:
- an EKO file is a tar file, e.g. `eko.tar`, with a specific internal structure
- the internal structure is currently dictated by a dedicated class in eko: [`eko.io.struct.InternalPaths`](https://github.com/NNPDF/eko/blob/master/src/eko/io/struct.py#L135), and it is:
    ```
    metadata.yaml
    theory.yaml
    operator.yaml
    recipes/
    parts/
    operators/
    ```
    this is pretty stable, and there is no foreseen change
- the user facing part is mostly `metadata.yaml` and `operators/`, both have an interface in EKO, specified by the dedicated classes (`eko.io.struct.Metadata`, and directly `eko.io.struct.EKO` for the second) - you might be interested in the original runcards, but they are there mainly for reference (usage required information is duplicated and possibly updated in `metadata.yaml`)
- the actual operators are stored in `operators/` in `.npy` format (or `.npz`, in case they include integration error) as rank 4 arrays
- the name reflects the value of their final scale, *but this is going to change* (because numerical FONLL will require to specify both the scale and the number of flavors, so the scale alone will be ambiguous)

**Comment by scarlehoff** [comment] 2023-03-29 07:35
In the atached `.tar.gz` you can find one grid, one eko and one script that does the `evolve` that pineko does. If inside the script you use the xgrid form axes instead of evolveinfo it works.

[tmp.tar.gz](https://github.com/NNPDF/pineko/files/11097713/tmp.tar.gz)

**Comment by cschwan** [comment] 2023-03-30 12:05
I'm not sure what's going on here, but It seems the EKO is wrong. How can I see the process-level x-grid values of the operator? Is there an easy way to extract them from the tarball?

**Comment by scarlehoff** [comment] 2023-03-30 12:10
I think you can obtain the grid you want doing:

```python
np.exp(operators.rotations.targetgrid.grid)
```

At the end of the script in the tarball (note the `np.exp` since the grid you get already had a `log` applied to this). This grid corresponds to the grid that pineappl returns when you do`evol_info`.

I would argue that even if the `eko` is wrong, `pineappl` should not return two different grids with `axes` and `evolve_info`.

**Comment by AleCandido** [comment] 2023-03-30 12:13
Another undocumented feature: [`Xgrid.raw`](https://github.com/NNPDF/eko/blob/f11827d8b8d67762ec5c1107557e4cfd57ab83be/src/eko/interpolation.py#L452) is a property showing exactly the raw grid, independently on being log or not.

Thus
```py
operators.rotations.targetgrid.raw
```
is what you want.

**Comment by cschwan** [comment] 2023-03-30 12:17
I need the x-grid values *at process level*, not a fit level. What you told me gives me points at fit level, I think.

**Comment by AleCandido** [comment] 2023-03-30 12:19
You're always thinking the opposite way of EKO: in principle, evolution is meant to evolve a fit at all scales, so the process-level grid is called `targetgrid`.
The `inputgrid` is for the fit-level input.

Of course, for FK-tables it works just the opposite.

**Comment by cschwan** [comment] 2023-03-30 13:58
This should be fixed in master, let me know if you need a prerelease.

**Comment by scarlehoff** [comment] 2023-03-30 14:24
Thanks! I justs tested it and seems to work ok.

Then #84 can be merged to master, but if you prefer @andreab1997 I can rerun theory 400 to ensure that fixing this grid didn't break any others.

 A pre-release will be needed I guess in order to make a release of pineko (I would put a minimum version of pineappl == 0.6.0 in #84 in any case... does poetry accept pre-releases @AleCandido -since I would need at least alpha.5)

**Comment by andreab1997** [comment] 2023-03-30 15:38
> Thanks! I justs tested it and seems to work ok.
> 
> Then #84 can be merged to master, but if you prefer @andreab1997 I can rerun theory 400 to ensure that fixing this grid didn't break any others.
> 
> A pre-release will be needed I guess in order to make a release of pineko (I would put a minimum version of pineappl == 0.6.0 in #84 in any case... does poetry accept pre-releases @AleCandido -since I would need at least alpha.5)

If you can rerun 400 please do it

**Comment by cschwan** [comment] 2023-03-30 16:39
@scarlehoff exactly, I only changed the numerical tolerance in functions called by `Grid::evolve`, and that leads to it finding the grid values it previously didn't find. `Grid::evolve_info` is unchanged.

I made another prelease here: <https://pypi.org/project/pineappl/0.6.0a5/>.

**Comment by scarlehoff** [comment] 2023-03-31 10:12
Ok, I've rerun all fktables, that worked, so this doesn't break any of them. Yey!

However, since we have the fktables from @andreab1997  I also did a 1-1 comparison between them using `convolute_with_one`... and those results are not that good...


For some datasets, such as `HERACOMB_SIGMARED_B.yaml` (HERA_NC_318GEV_EAVG_SIGMARED_BOTTOM) I get differences beyond the % level.

```
>>> new_results
array([0.00119094, 0.0023079 , 0.00400382, 0.00271623, 0.00514309,
       0.00322998, 0.00218821, 0.00542587, 0.01225607, 0.01073866,
       0.00809805, 0.0059266 , 0.004914  , 0.0032805 , 0.01587305,
       0.01319804, 0.01007652, 0.00752765, 0.02447162, 0.01361705,
       0.00881446, 0.02106204, 0.01058296, 0.00814256, 0.02137009,
       0.00944453, 0.00827178])
>>> good_results
array([0.00119224, 0.0023125 , 0.00401096, 0.00272189, 0.00515239,
       0.00323755, 0.00219423, 0.00543734, 0.01221178, 0.01070744,
       0.00808576, 0.00592559, 0.0049167 , 0.00328678, 0.01583355,
       0.01317095, 0.01006146, 0.00752021, 0.02440836, 0.01358561,
       0.00879478, 0.02100241, 0.01055086, 0.00811102, 0.02013338,
       0.00871796, 0.00777171])
``` 

And after a few checks I can confirm that these differences are due to the EKO. I get the same result, it doesn't matter whether I use `main` or `remove_axes_call` (so I would say #84 is ok, in the sense that it doesn't generate a regression)

but if I use the `ekos` that @andreab1997 has in his folder for 4244 I get his fktables (even if I evolve them with my branch)

----
Then I tested against the fktables that we have in the server and those are again different but I'm not sure whether they are supposed to be different anyway...

Not sure what to make of this... if you think this is enough to merge #84 please do. If you want to investigate this further... let me know.

**Comment by andreab1997** [comment] 2023-03-31 10:17
> Ok, I've rerun all fktables, that worked, so this doesn't break any of them. Yey!
> 
> However, since we have the fktables from @andreab1997 I also did a 1-1 comparison between them using `convolute_with_one`... and those results are not that good...
> 
> For some datasets, such as `HERACOMB_SIGMARED_B.yaml` (HERA_NC_318GEV_EAVG_SIGMARED_BOTTOM) I get differences beyond the % level.
> 
> ```
> >>> new_results
> array([0.00119094, 0.0023079 , 0.00400382, 0.00271623, 0.00514309,
>        0.00322998, 0.00218821, 0.00542587, 0.01225607, 0.01073866,
>        0.00809805, 0.0059266 , 0.004914  , 0.0032805 , 0.01587305,
>        0.01319804, 0.01007652, 0.00752765, 0.02447162, 0.01361705,
>        0.00881446, 0.02106204, 0.01058296, 0.00814256, 0.02137009,
>        0.00944453, 0.00827178])
> >>> good_results
> array([0.00119224, 0.0023125 , 0.00401096, 0.00272189, 0.00515239,
>        0.00323755, 0.00219423, 0.00543734, 0.01221178, 0.01070744,
>        0.00808576, 0.00592559, 0.0049167 , 0.00328678, 0.01583355,
>        0.01317095, 0.01006146, 0.00752021, 0.02440836, 0.01358561,
>        0.00879478, 0.02100241, 0.01055086, 0.00811102, 0.02013338,
>        0.00871796, 0.00777171])
> ```
> 
> And after a few checks I can confirm that these differences are due to the EKO. I get the same result, it doesn't matter whether I use `main` or `remove_axes_call` (so I would say #84 is ok, in the sense that it doesn't generate a regression)
> 
> but if I use the `ekos` that @andreab1997 has in his folder for 4244 I get his fktables (even if I evolve them with my branch)
> 
> Then I tested against the fktables that we have in the server and those are again different but I'm not sure whether they are supposed to be different anyway...
> 
> Not sure what to make of this... if you think this is enough to merge #84 please do. If you want to investigate this further... let me know.

So I would say that this is normal because those ekos I produced are produced with a branch of eko (that will be merged soon) because there the factorization scale variation was fixed. So if you produced the ekos with master of course they do not agree. In the server instead I should have exactly the same fks I have in dom.

**Comment by scarlehoff** [comment] 2023-03-31 10:19
If I use your ekos I get your fktables (meaning, the ones that I can find in dom for theory 4244). Is that correct?
If I use mine I don't (but mine agree with what one would get with master).

**Comment by andreab1997** [comment] 2023-03-31 10:33
> If I use your ekos I get your fktables (meaning, the ones that I can find in dom for theory 4244). Is that correct? If I use mine I don't (but mine agree with what one would get with master).

yes exactly but you should also get exactly the same if you compare with the ones in the server. I mean, the fktables in 4244 are exactly the same (for DIS) of the ones in theory_424 in the server

**Comment by andreab1997** [comment] 2023-03-31 10:34
Anyway if the central eko (meaning the one without fact scale variations) changes between master and the branch I am using that is something that @felixhekhorn and @AleCandido should know.

**Comment by andreab1997** [comment] 2023-03-31 10:40
> Ah, ok. No, I'm not looking at the sever. I'm really looking at the ones you have in your folder.
> 
> So then what do you think? Should we merge #84? It seems to be compatible with `master` and in any case it will be overwritten by your PR.
> 
> > Anyway if the central eko (meaning the one without fact scale variations) changes between master and the branch I am using that is something that @felixhekhorn and @AleCandido should know.
> 
> Note that I'm not creating ekos with your branch but using the ones you already had there.

Yes but those ekos should be ok, I computed with that branch. I guess we can merge #84.

**Comment by scarlehoff** [comment] 2023-03-31 10:41
ok. Btw, the fact that theory 400 is different (the one in the server) is expected right? (and, accordingly, theory 400 should not be used for "real" fits yet)?

**Comment by andreab1997** [comment] 2023-03-31 10:48
> ok. Btw, the fact that theory 400 is different (the one in the server) is expected right? (and, accordingly, theory 400 should not be used for "real" fits yet)?

No it is strange now because I updated it yesterday I believe.

**Comment by scarlehoff** [comment] 2023-03-31 10:49
I was using theory 400 to check the hadronic fktables (and some did change)

**Comment by andreab1997** [comment] 2023-03-31 10:53
> I was using theory 400 to check the hadronic fktables (and some did change)

Hadronic make sense. Perfect, they were not updated

**Closed** 2023-03-31 14:00 UTC
Labels: refactor
